//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnigramsProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnigramsProject()
        {
            this.AnigramsCharacters = new HashSet<AnigramsCharacter>();
            this.AnigramsReviews = new HashSet<AnigramsReview>();
        }
    
        public int ProjectID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SquareThumb { get; set; }
        public string PortraitThumb { get; set; }
        public string Tagline { get; set; }
        public string Summary { get; set; }
        public string Link { get; set; }
        public string SideContent { get; set; }
        public string ShortDescription { get; set; }
        public string ShortTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnigramsCharacter> AnigramsCharacters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnigramsReview> AnigramsReviews { get; set; }
    }
}
