//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnigramsCharacter
    {
        public int CharacterID { get; set; }
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
    
        public virtual AnigramsProject AnigramsProject { get; set; }
    }
}
