//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnigramsReview
    {
        public int ReviewID { get; set; }
        public int ProjectID { get; set; }
        public string Author { get; set; }
        public string AuthorLink { get; set; }
        public string ReviewLink { get; set; }
        public string Description { get; set; }
    
        public virtual AnigramsProject AnigramsProject { get; set; }
    }
}
