//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenLanguageSymbol
    {
        public int LanguageSymbolID { get; set; }
        public int LanguageID { get; set; }
        public int SymbolID { get; set; }
        public string Examples { get; set; }
    
        public virtual GenLanguage GenLanguage { get; set; }
        public virtual GenSymbol GenSymbol { get; set; }
    }
}
