//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenLanguage()
        {
            this.GenLanguageSymbols = new HashSet<GenLanguageSymbol>();
            this.GenSuffixes = new HashSet<GenSuffix>();
        }
    
        public int LanguageID { get; set; }
        public string Name { get; set; }
        public bool Gendered { get; set; }
        public string Structure { get; set; }
        public Nullable<bool> AdjectiveBefore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenLanguageSymbol> GenLanguageSymbols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenSuffix> GenSuffixes { get; set; }
    }
}
