//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenSymbol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenSymbol()
        {
            this.GenLanguageSymbols = new HashSet<GenLanguageSymbol>();
        }
    
        public int SymbolID { get; set; }
        public string Symbol { get; set; }
        public string Code { get; set; }
        public string English { get; set; }
        public bool IsVowel { get; set; }
        public Nullable<bool> IsSeparator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenLanguageSymbol> GenLanguageSymbols { get; set; }
    }
}
