//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsProductionsV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenSuffix
    {
        public int SuffixID { get; set; }
        public int LanguageID { get; set; }
        public string Native { get; set; }
        public string Phonetic { get; set; }
        public string Code { get; set; }
        public string Gender { get; set; }
        public string Meaning { get; set; }
        public string Type { get; set; }
    
        public virtual GenLanguage GenLanguage { get; set; }
    }
}
